name: Add Issue to Project Todo Column

on:
  issues:
    types: [opened]

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.SECRET_PAT }}
      ISSUE_URL: ${{ github.event.issue.html_url }}
      PROJECT_OWNER: your-org-or-username
      PROJECT_NUMBER: your-project-number

    steps:
      - name: Install GitHub CLI
        run: sudo apt update && sudo apt install -y gh jq

      - name: Authenticate GitHub CLI
        run: echo "${GITHUB_TOKEN}" | gh auth login --with-token

      - name: Get Project ID
        run: |
          PROJECT_ID=$(gh project view $PROJECT_NUMBER --owner $PROJECT_OWNER --format json | jq -r '.id')
          echo "Project ID: $PROJECT_ID"
          echo "PROJECT_ID=$PROJECT_ID" >> $GITHUB_ENV

      - name: Add Issue to Project
        run: |
          ITEM_ID=$(gh project item-add $PROJECT_NUMBER --owner "$PROJECT_OWNER" --url "$ISSUE_URL" --format json | jq -r '.id')
          echo "ITEM_ID: $ITEM_ID"
          echo "ITEM_ID=$ITEM_ID" >> $GITHUB_ENV

          if [ -z "$ITEM_ID" ]; then
            echo "Error: Failed to add issue to project."
            exit 1
          fi

      - name: Get Status Field and ToDo Option ID
        run: |
          FIELDS=$(gh project field-list $PROJECT_NUMBER --owner "$PROJECT_OWNER" --format json)
          STATUS_FIELD=$(echo "$FIELDS" | jq -r '.fields[] | select(.name == "Status")')
          STATUS_FIELD_ID=$(echo "$STATUS_FIELD" | jq -r '.id')
          TODO_OPTION_ID=$(echo "$STATUS_FIELD" | jq -r '.options[] | select(.name == "Todo") | .id')

          echo "STATUS_FIELD_ID: $STATUS_FIELD_ID"
          echo "TODO_OPTION_ID: $TODO_OPTION_ID"

          echo "STATUS_FIELD_ID=$STATUS_FIELD_ID" >> $GITHUB_ENV
          echo "TODO_OPTION_ID=$TODO_OPTION_ID" >> $GITHUB_ENV

          if [ -z "$STATUS_FIELD_ID" ] || [ -z "$TODO_OPTION_ID" ]; then
            echo "Error: Could not find Status field or Todo option."
            exit 1
          fi

      - name: Set Issue Status to Todo
        run: |
          RESULT=$(gh project item-edit $PROJECT_NUMBER \
            --id "$ITEM_ID" \
            --project-id "$PROJECT_ID" \
            --field-id "$STATUS_FIELD_ID" \
            --single-select-option-id "$TODO_OPTION_ID" \
            --format json)

          echo "RESULT: $RESULT"

          if echo "$RESULT" | jq -e '.id' > /dev/null; then
            echo "Issue successfully added to project and set to Todo status."
          else
            echo "Error updating issue status: $RESULT"
            exit 1
          fi
